#!/usr/bin/env bash
#Install Fabric for Python 3 - version 1.14.post1

# Install necessary packages
sudo apt-get update
sudo apt-get install -y libffi-dev libssl-dev build-essential libexpat1-dev libpython3-dev libpython3.8-dev

# Check if Python3 and pip3 are installed, install them if not
if ! command -v python3 &> /dev/null; then
	    sudo apt-get install -y python3
fi

if ! command -v pip3 &> /dev/null; then
	    sudo apt-get install -y python3-pip
fi

pip3 uninstall Fabric
sudo apt-get install libffi-dev
sudo apt-get install libssl-dev
sudo apt-get install build-essential
sudo apt-get install python3.4-dev
sudo apt-get install libpython3-dev
pip3 install pyparsing
pip3 install appdirs
pip3 install setuptools==40.1.0
pip3 install cryptography==2.8
pip3 install bcrypt==3.1.7
pip3 install PyNaCl==1.3.0
pip3 install Fabric3==1.14.post1
